language: go

go:
  - "1.15.5"
  - master

os:
  - linux

dist: xenial

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  global:
    - GO111MODULE=on
    - GORACE="halt_on_error=1"

script:
  - set -eo pipefail
  # We could merge the two commands behind for efficiency, but it would give less comprehensive errors
  # Check files syntax and basic formatting
  - echo "Files with syntax or formatting errors :"
  - find . -name "*.go" -execdir gofmt -l -s '{}' \+
  # Check files formatting, including imports
  - echo "Files with formatting errors :"
  - find . -name "*.go" -execdir goimports -l '{}' \+
  # Run the test suite
  - go test -v ./...

# whitelist long living branches to avoid testing feature branches twice (as branch and as pull request)
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.x$/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
