name: continuous integration
on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: test
    strategy:
      matrix:
        go-version: ['^1.14.6']
    steps:
      - uses: actions/checkout@v2
      - name: golang-setup
        uses: actions/setup-go@v2
        with:
          go-version:  ${{ matrix.go-version }}
      - name: test
        run: |
          go test ./...
